### ISSUE TITLE
Mauvais directory d'install

### ISSUE THREAD

**Issue by PeignoirRose** [kube/42homebrew_fix#8]
bonjour !
J'essaie d'installer ctags via brew, soucis : il tente d'installer dans la library (pour laquelle nous n'avons pas les droits) au lieu du .brew 
plusieurs uinstall/reinstall apres rien n'y fait !
Une idee ? :/

merci !

**Comment by kube** [comment]
Ça n'est pas lié directement à Homebrew, ni à ce script d'install.

Je t'invite à lire la [formule d'installation de ctags](https://github.com/Homebrew/homebrew-core/blob/30abddeed8f2b8d6e3d7b5ee313ddcd2c8ff1671/Formula/ctags.rb#L38).
